# Generated by Django 2.2.11 on 2020-04-28 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techs', '0001_initial'),
        ('exam', '0002_auto_20200428_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='satisfactory_rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='exam',
            name='techs',
            field=models.ManyToManyField(related_name='exams', to='techs.Technology'),
        ),
    ]
