version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: django-Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code 
    ports:
      - 8000:8000
      - 8888:8888 # for debugging(ptvsd)
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testing321
      - POSTGRES_DB=icode

  redis:
    image: redis:5.0.9-alpine
    ports: 
      - 6379:6379
    volumes: 
      - redis_data:/var/lib/redis/data/

volumes:
  postgres_data:
  redis_data:
